package com.doubleclue.dcem.recruiting.entities.enums;

public enum Nationality {
	
	Afghan("AF"), 
	Alander("AX"),
	Albanian("AL"),
	Algerian("DZ"),
	American("US"),
	American_("UM"),
	American_Samoan("AS"),
	American_Virgin_Islander("VI"),
	Andorran("AD"),
	Angolan("AO"),
	Anguillan("AI"),
	Antarctican("AQ"),
	Antiguan$Barbudan("AG"),
	Argentinian("AR"),
	Armenian("AM"),
	Aruban("AW"),
	Australian("AU"),
	Austrian("AT"),
	Azerbaijani("AZ"),
	
	Bahamian("BS"),
	Bahraini("BH"),
	Bangladeshi("BD"),
	Barbadian("BB"),
	Belarusian("BY"),
	Belgian("BE"),
	Belizean("BZ"),
	Beninese("BJ"),
	Bermudian("BM"),
	Bhutanese("BT"),
	Bolivian("BO"),
	Bonairean("BQ"),
	Bosnian$Herzegovinian("BA"),
	Botswanan("BW"),
	Bouvet_Islander("BV"),
	Brazilian("BR"),
	British("GB"),
	British_("IO"),
	British_Virgin_Islander("VG"),
	Bruneian("BN"),
	Bulgarian("BG"),
	Burkinabe("BF"),
	Barundi("BI"),
	
	Cabo_Verdean("CV"),
	Cambodian("KH"),
	Cameroonian("CM"),
	Canadian("CA"),
	Caymanian("KY"),
	Central_African("CF"),
	Chadian("TD"),
	Chilean("CL"),
	Chinese("CN"),
	Christmas_Islander("CX"),
	Cocos_Islander("CC"),
	Colombian("CO"),
	Comorian("KM"),
	Congolese("CG"),
	Congolese_("CD"),
	Cook_Islander("CK"),
	Costa_Rican("CR"),
	Croatian("HR"),
	Cuban("CU"),	
	Curacaoan("CR"),
	Cypriot("CY"),
	Czech("CZ"),
	
	Danish("DK"),	
	Djiboutian("DJ"),
	Dominican("DM"),
	Dominican_("DO"),
	Dutch("NL"),
	Dutch_("BQ"),
	
	Ecuadorean("EC"),
	Egyptian("EG"),
	Equatoguinean("GQ"),
	Emirati("AE"),
	Eritrean("ER"),
	Estonian("EE"),
	Ethiopian("ET"),
	
	Falkland_Islander("FK"),
 	Faroese("FO"),
	Fijian("FJ"),
	Filipino("PH"),
	Finnish("FI"),
	French("FR"),
	French_("TF"),
 	French_Guianese("GF"),
	French_Polynesian("PF"),
	
	Gabonese("GA"),
	Gambian("GM"),
	Georgian("GE"),
	German("DE"),	
	Ghanaian("GH"),
 	Gibraltarian("GI"),
	Greek("GR"),
 	Greenlander("GL"),
	Grenadian("GD"),
	Guadeloupeans("GP"),
	Guamanian("GU"),
	Guatemalan("GT"),
	Guern("GG"),
	Guinean("GN"),
 	Bissau0Guineans("GW"),
	Guyanese("GY"),	
	
	Haitian("HT"),
    Heard$McDonald_Islanders("HM"),
	Honduran("HN"),
	Honkonger("HK"),
	Hungarian("HU"),
	
	Icelander("IS"),
	Indian("IN"),
	Indonesian("ID"),
	Iranian("IR"),
	Iraqi("IQ"),
	Ireland("IE"),
	Israeli("IL"),
	Italian("IT"),
	Ivorian("CI"),
	
	Jamaican("JM"),
	Japanese("JP"),
	Jersian("JE"),
	Jordanian("JO"),
	
	Kazakh("KZ"),
	Kenyan("KE"),
	Kiribati("KI"),	
	Kuwaiti("KW"),
    Kyrgyzstani("KG"),
    
    Lao("LA"),
	Latvian("LV"),
	Lebanese("LB"),
	Liberian("LR"),
	Libyan("LY"),
 	Liechtensteiner("LI"),
	Lithuanian("LT"),
	Luxembourger("LU"),
	
    Macanese("MO"),
 	Macedonian("MK"),
	Madagascan("MG"),
 	Mahorans("YT"),
	Malawian("MW"),
	Malaysian("MY"),
	Maldivian("MV"),
	Malian("ML"),
	Maltese("MT"),
	Marshallese("MH"),
	Manx("IM"),
	Martiniquais("MQ"),
	Mauritanian("MR"),
	Mauritian("MU"),
	Mexican("MX"),
	Micronesian("FM"),
	Moldovan("MD"),
	Monacan("MC"),
	Mongolian("MN"),
	Montenegrin("ME"),
	Montserratian("MS"),
	Moroccan("MA"),
	Mosotho("LS"),
	Mozambican("MZ"),
	Myanmar("MM"),
	
	Namibian("NA"),
 	Nauruan("NR"),
	Nepalese("NP"),
 	New_Caledonian("NC"),
	New_Zealander("NZ"),
	Nicaraguan("NI"),
	Nigerien("NE"),
	Nigerian("NG"),
 	Niuean("NU"),
 	Norfolk_Islander("NF"),
	North_Korean("KP"),
 	Northern_Marianan("MP"),
	Norwegian("NO"),
	
	Omani("OM"),
	
	Pakistani("PK"),
 	Palauan("PW"),
 	Palestinian("PS"),
	Panamanian("PA"),
	Papuan("PG"),
	Paraguayan("PY"),
	Peruvian("PE"),
 	Pitcairn_Islander("PN"),
	Polish("PL"),
	Portuguese("PT"),
 	Puerto_Rican("PR"),
 	
	Qatari("QA"),

    Reunionese("RE"),
	Romanian("RO"),
	Russian("RU"),
	Rwandan("RW"),
	
	Barthelemois("BL"),
 	Saint_Helenian("SH"),
    Kittitians$Nevisians("KN"),
 	Saint_Lucian("LC"),
 	Saint$Martinoise("MF"),
    Saint0Pierrais$Miquelonnais("PM"),
    Vincentians("VC"),
	Salvadorean("SV"),
	Samoan("AS"),
 	Sammarinese("SM"),
 	Sao_Tomeans("ST"),
	Saudi_Arabian("SA"),
	Senegalese("SN"),
	Serbian("RS"),
 	Seychellois("SC"),
	Sierra_Leonian("SL"),
	Singaporean("SG"),
 	Sint_Maartener("SX"),
	Slovakian("SK"),
	Slovenian("SI"),
	Solomon_Islander("SB"),
	Somali("SO"),
	South_African("ZA"),
    South_Georgia$Sandwich_Islanders("GS"),
	South_Korean("KR"),
	South_Sudanese("SS"),
	Spanish("ES"),
	Sri_Lankan("LK"),
	Sudanese("SD"),
	Surinamer("SR"),
	Norwegian_("SJ"),
	Swedish("SE"),
	Swiss("CH"),
	Swazi("SZ"),
	Syrian("SY"),
	
	Taiwanese("TW"),
 	Tajikistani("TJ"),
 	Tanzanian("TZ"),
	Thai("TH"),
	Timorese("TL"),
	Togolese("TG"),
 	Tokelauan("TK"),
 	Tongan("TO"),
	Trinidadian$Tobagonian("TT"),
	Tunisian("TN"),
	Turkish("TR"),
 	Turkmen("TM"),
 	Turks_and_Caicos_Islander("TC"),
	Tuvaluan("TV"),
	
	Ugandan("UG"),
	Ukrainian("UA"),
	Uruguayan("UY"),
    Uzbekistani("UZ"),
	
	Vanuatuan("VU"),
 	Vaticanian("VA"),
	Venezuelan("VE"),
	Vietnamese("VN"),
	
	Wallisians$Futunans("WF"),
	Sahrawi("EH"),
	
	Yemeni("YE"),
	
	Zambian("ZM"),
 	Zimbabwean("ZW");
 	
	private String countryCode;
	
	private Nationality(String countryCode) {
		this.countryCode = countryCode;
	}
	
	public String getCountryCode() {
		return countryCode;
	}
	
	@Override
	public String toString() {
		String country = this.name();
		
		if(country.contains("_")) {
			country = country.replace("_", " ");
		}
		
		if(country.contains("$")) {
			country = country.replace("$", "/");
		}
		
		if(country.contains("0")) {
			country = country.replace("0", "-");
		}
		
		return country;
	}
}
